name: Bug Report
description: 报告 dk 命令或 Web 控制台的问题
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: 问题描述
      placeholder: dk list 显示的余额不正确...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 复现步骤
      placeholder: |
        1. 运行 `dk add <key>`
        2. 运行 `dk list`
        3. 余额显示为 0，但实际有额度
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: 操作系统
      options:
        - macOS
        - Windows (PowerShell)
        - Linux
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: 问题模块
      options:
        - CLI 命令行
        - Web 控制台
        - Electron 桌面端
    validations:
      required: true

  - type: dropdown
    id: command
    attributes:
      label: 相关命令
      description: 如果是 CLI 问题，选择相关命令
      options:
        - dk add (添加密钥)
        - dk list (列出密钥)
        - dk current (当前密钥)
        - dk use (切换密钥)
        - dk rm (删除密钥)
        - dk run (运行命令)
        - dk serve (启动服务)
        - dk reinstall (重装)
        - dk uninstall (卸载)
        - 不适用

  - type: textarea
    id: logs
    attributes:
      label: 错误日志
      description: 粘贴终端输出或 `~/.oroio/serve.log`
      render: shell
