name: Feature Request
description: 提议新的 dk 命令或功能改进
labels: ["feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: 使用场景
      placeholder: |
        我有多个 Factory 账号，需要频繁切换...
        或者：dk list 查询太慢，希望能缓存更久...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 建议方案
      placeholder: |
        添加 `dk profile` 命令支持多配置切换
        或者：增加 DKM_CACHE_TTL 环境变量
    validations:
      required: true

  - type: checkboxes
    id: component
    attributes:
      label: 涉及模块
      options:
        - label: CLI 命令行
        - label: Web 控制台
        - label: Electron 桌面端
        - label: 安装/部署

  - type: checkboxes
    id: contribution
    attributes:
      label: 贡献意愿
      options:
        - label: 我愿意提交 PR 来实现
